# Detector params
image_topic: /asus/rgb/image_raw
points_topic: left/points
output_topic: left/result
publish_images: true
stereo_vision: false

# Monocular stereopsis params
pub_topic: triangulation/points
stereo_baseline: 0.12
monocular: true
monocular_topic: left/points
diameter: 0.2 # in m