# Detector params
image_topic: /bumblebee2/left/image_raw
points_topic: left/points
output_topic: left/result
publish_images: true
stereo_vision: false

# Monocular stereopsis params
pub_topic: triangulation/points
#left_camera_calibration: /home/charlie/Workspace/ROS/obs_avoidance_ws/src/rovi2_demo_manager/config/bumblebee_left.yaml
#right_camera_calibration: /home/charlie/Workspace/ROS/obs_avoidance_ws/src/rovi2_demo_manager/config/bumblebee_right.yaml
stereo_baseline: 0.12
monocular: true
monocular_topic: left/points
diameter: 0.2 # in m